### ISSUE TITLE
Equal's Corner Left Turn Confusion

### ISSUE THREAD

**Issue by EngineerToast** [BigZaphod/Taxi#2]
First, I _super_ don't know how to use git so I apologize if this is the improper means by which to communicate this to you. I code for fun and I think Taxi is a hoot. I've even figured out a way to call functions but, dang, it's messy. Equal's Corner is giving me trouble, though, and I yearn to see Taxi perfected that one little bit more.

I use [TIO](https://tio.run/#taxi) to write Taxi code and have found a point of confusion when heading north from Equal's Corner and then turning left. I asked Dennis about it and [he said that](https://chat.stackexchange.com/transcript/message/39771251#39771251)  TIO uses the official interpreter and linked to this repository. Here's my original question to him:

I think there's an error in the Taxi map. At the very least, it doesn't seem to match the map posted on bigzaphod.github.io/Taxi . Specifically, TIO does not seem to include the first left turn when heading north from Equal's Corner. Here's a quick test program that errors out with "cannot drive in that direction":
[https://tio.run/##lY6xDsIwDET3fsVtbJXK2BUhJhASX2CVKLUIcXEStXx9KI0YKjHAYlu@092LNHHODThgJI7sLSjiEkm7nt0Vp3Q3Kk7ss65@cx0EUb5q7YgGDlvossvt6urM3S0NIAwUgvHWKKy8O@ac/SOR2wTsRL3R/7yFZP0tDB9tnkdR0/oFJOcX](https://tio.run/##lY6xDsIwDET3fsVtbJXK2BUhJhASX2CVKLUIcXEStXx9KI0YKjHAYlu@092LNHHODThgJI7sLSjiEkm7nt0Vp3Q3Kk7ss65@cx0EUb5q7YgGDlvossvt6urM3S0NIAwUgvHWKKy8O@ac/SOR2wTsRL3R/7yFZP0tDB9tnkdR0/oFJOcX)
Contrast to this program which errors out with being fired for not returning to the garage:
[https://tio.run/##lU4xDsIwENv7Cm9slcrYFSEmEBIvOJUoPRFy5ZKo5fWhNGKoxADL@WRbtiNNnHMDDhiJI3sLirhE0q5nd8Up3Y2KE/usq99cB0GUr1o7ooHDFrpg@V1dnbm7pQGEgUIw3hqFlXfHnLN/JHKbgJ2oN/qftyxZs2XDR5vvUdS0fiFzfgE](https://tio.run/##lU4xDsIwENv7Cm9slcrYFSEmEBIvOJUoPRFy5ZKo5fWhNGKoxADL@WRbtiNNnHMDDhiJI3sLirhE0q5nd8Up3Y2KE/usq99cB0GUr1o7ooHDFrpg@V1dnbm7pQGEgUIw3hqFlXfHnLN/JHKbgJ2oN/qftyxZs2XDR5vvUdS0fiFzfgE)

I realize you are not responsible for how TIO runs but I was hoping you could help as I think I have identified the cause of my confusion: the first left turn to the north of Equal's Corner (the continuation of the road for Starchild Numerology) does not count as a turn because there are no nodes in that direction. As such, it's as if the road doesn't exist insofar as the interpreter is concerned. However, it very much exists on the graphical map.

As far as I can tell, there are no other valid paths where you pass a dead-end, empty road and then later turn in the same direction as that empty road. Rounder's Pub has such a road on the left but you have to turn right for it to be a valid path. This may be the only instance where this is a problem.

Can you confirm that this is an issue? If it is, can you open that repo you haven't touched in 6 years (except for Dennis's pull request from TIO) and correct it? I imagine the easiest way would be to modify the graphical map to drop the dead road.

If you're still reading this, then I appreciate your time.

**Comment by BigZaphod** [comment]
Oh wow.. someone is using Taxi!

:P

I guess it could be argued that since the map shows a dead end road there, it should still count as a “left turn”, but the way it was implemented is that it only considers it a turn if there’s actually a node down the road in that direction somewhere. So that’s why there’s no left turn at that intersection as far as the interpreter is concerned.

Probably the map should be cleaned up to eliminate these ambiguities, but a bit of artistic license had been applied to it. :P 

If I made any changes to these rules, then I suspect a ton of existing programs would stop working as left/right counts would end up being wrong in places so I’m not sure I should do that.

I’m glad you’re having fun playing with Taxi! It was a silly project. :)

l8r
Sean
